theme: jekyll-theme-minimal
title: The Undocumented Analysts
description: An analysis of key factors to critical and commercial successes in the movie industry over time.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Section
    url: /
  - title: Example
    url: example
